version: "1"

services:
  postgresql:
    container_name: postgresql
    image: postgres:14
    environment:
      POSTGRES_USER: ilya
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: scrapper
    volumes:
      - ./postgres-data:/data/
    ports:
      - "5432:5432"
    networks:
      - backend

  liquibase-migrations:
    container_name: liquibase
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=ilya
      - --password=123
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

networks:
  backend:
    driver: bridge