/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.ChatLink;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ChatLinkRecord extends UpdatableRecordImpl<ChatLinkRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chat_link.chat_link_id</code>.
     */
    public void setChatLinkId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chat_link.chat_link_id</code>.
     */
    public Integer getChatLinkId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.chat_link.chat_id</code>.
     */
    public void setChatId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chat_link.chat_id</code>.
     */
    public Integer getChatId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.chat_link.link_id</code>.
     */
    public void setLinkId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.chat_link.link_id</code>.
     */
    public Integer getLinkId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ChatLink.CHAT_LINK.CHAT_LINK_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ChatLink.CHAT_LINK.CHAT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return ChatLink.CHAT_LINK.LINK_ID;
    }

    @Override
    public Integer component1() {
        return getChatLinkId();
    }

    @Override
    public Integer component2() {
        return getChatId();
    }

    @Override
    public Integer component3() {
        return getLinkId();
    }

    @Override
    public Integer value1() {
        return getChatLinkId();
    }

    @Override
    public Integer value2() {
        return getChatId();
    }

    @Override
    public Integer value3() {
        return getLinkId();
    }

    @Override
    public ChatLinkRecord value1(Integer value) {
        setChatLinkId(value);
        return this;
    }

    @Override
    public ChatLinkRecord value2(Integer value) {
        setChatId(value);
        return this;
    }

    @Override
    public ChatLinkRecord value3(Integer value) {
        setLinkId(value);
        return this;
    }

    @Override
    public ChatLinkRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatLinkRecord
     */
    public ChatLinkRecord() {
        super(ChatLink.CHAT_LINK);
    }

    /**
     * Create a detached, initialised ChatLinkRecord
     */
    public ChatLinkRecord(Integer chatLinkId, Integer chatId, Integer linkId) {
        super(ChatLink.CHAT_LINK);

        setChatLinkId(chatLinkId);
        setChatId(chatId);
        setLinkId(linkId);
    }
}
